### ISSUE TITLE
please

### ISSUE THREAD

**Issue by devoss62** [LeClubSandwichStudio/MUR#11]
Hello,

missing the pusher and a guide piece?

Sylvain,

![ValveV4 0-v40](https://user-images.githubusercontent.com/55943394/78366554-f56db600-75c0-11ea-9673-5c977fea48ad.png)

**Comment by cquest** [comment]
The pusher is not 3D printed. We're about to publish a much more detailed set of documents (WIP).

**Comment by DoubleCigogne** [comment]
These parts are in the BOM and they are not 3D Printed. 
They are :
- T8x4 screw from a 3D printer
- T8x4 Brass nut from a 3D printer
