### ISSUE TITLE
In the first comment there seem to be a typo between 180 and 160

### ISSUE THREAD

**Issue by MCMic** [LeClubSandwichStudio/MUR#2]
Maybe I misunderstood but it seems to me lines 52/53 should state 180 like the ones before and after, or the other ones are wrong and should state 160 as well, not sure?

https://github.com/LeClubSandwichStudio/MUR/blob/d80a23c6057c3697014bc0ded8df49dc8f256d1d/V0/software/MUR.ino#L52

**Comment by LeSuedois** [comment]
Hello,
sorry but this value is still in work in progress. We started with 180° and lowered it to 60° now with our new (and better) airvalves. another positive aspect is that the movement is much faster and reduced wear on those cheap servos. 
As written in the comments this value changes from servo to servo and must be tweaked to match your hardware!

**Comment by LeSuedois** [comment]
please wait for major update coming this weekend. we only publish once tested in medical environment
