### ISSUE TITLE
Bill of Materials

### ISSUE THREAD

**Issue by Jacoby6000** [LeClubSandwichStudio/MUR#8]
For people to start building these rapidly in local communities, it would be helpful to have a BOM in CSV form which people can reference for when they're gathering supplies.  Here's an example of what I mean:  https://docs.google.com/spreadsheets/d/1Eib0IkmRiP-zVM2p6gZ9PJ2bsDDvSKWbGtUybuFWfcs/edit#gid=1276357080

I'll start working on putting this together in my freetime when I can.

**Comment by LeSuedois** [comment]
Please wait a bit... We are finishing the documentation and update master soon.
BTW, I know what's CSV...
